### PR TITLE
Add existing packages from wbond's default repository

### PR DESCRIPTION
**Pull request by rwols**

### CODE REVIEW

**Comment by rchl** [comment]
Also move `lsp_utils`? :)

**Comment by predragnikolic** [comment]
I will have to read the documentation and look at few examples online to have a feel for setting up PC reposities 🙂

Should all those packages be removed from the default PC repository, before adding the our new repository to PC? (I imagine that packages will be missing on PC for a bit)

**Comment by rchl** [comment]
> Should all those packages be removed from the default PC repository, before adding the our new repository to PC? (I imagine that packages will be missing on PC for a bit)

Those will be removed from PC at the same time when adding this repository.

**Comment by predragnikolic** [comment]
Can you move dependencies to a repository? For some reason I dont think it is possible, but will look in the docs

**Review by rchl — APPROVED** [review]

**Pull request merged**
