### PR TITLE
Test bot from forked repo

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by rchl** [comment]
Hmm...

When pull request is triggered from a fork then the `$GITHUB_TOKEN` token has only permission to that forked repo?

And the note in the organization-wide tokens also says:
> Secrets are not passed to workflows that are triggered by a pull request from a fork.

So how the hell am I supposed to post review comments when PR is triggered from a fork?
Maybe I'm missing something? Do you understand that @rwols?

**Comment by rwols** [comment]
The issue is that a fork may alter the workflow files for malicious purposes. Perhaps you could try the pull_request_target event, instead of the pull_request event. https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by rchl** [comment]
In that case, I think it makes sense to separate the review bot into its own repository as otherwise there is still a risk of bad things happening if a bad actor modifies the code of the scripts.

**Comment by rchl** [comment]
It works with `pull_request_target` event.

I've separated test code into their own repos as, as I've said, it would be potentially unsecured to run it from the main repo.

Here are two actions I've created:
 - https://github.com/sublimelsp/st-package-reviewer-action
 - https://github.com/sublimelsp/st-schema-reviewer-action

Those are separated because I need to run both for PRs but only the latter one for commits on `main` and there is no support for conditionally running steps in those `composite actions` currently.

**Comment by rwols** [comment]
Pretty cool!

**Pull request closed without merging**
